build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: functionary-medium-v3.2
python_version: py310
requirements:
- transformers==4.43.3
- accelerate==0.21.0
- sentencepiece~=0.1.99
- pydantic==2.6.0
- scipy==1.11.1
- jsonref==1.1.0
- requests==2.31.0
- protobuf==3.20.0
- tokenizers==0.19.1
- vllm==0.5.4
- json_source_map==1.0.5
- jinja2==3.1.4
resources:
  accelerator: A100:2
  cpu: '3'
  memory: 24Gi
  use_gpu: true
secrets: {}
system_packages: []
